apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: applicationpipeline
    name: applicationpipeline
  name: applicationpipeline
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    type: None
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |
        #!groovy
        node('maven') {
          stage 'build & deploy in dev'
          openshiftBuild(namespace: 'development',
                    buildConfig: 'myapp',
                  showBuildLogs: 'true',
                  waitTime: '3000000')

          stage 'verify deploy in dev'
          openshiftVerifyDeployment(namespace: 'development',
                      depCfg: 'myapp',
                      replicaCount:'1',
                      verifyReplicaCount: 'true',
                      waitTime: '300000')

          stage 'deploy in test'
          openshiftTag(namespace: 'development',
                  sourceStream: 'myapp',
                sourceTag: 'latest',
                destinationStream: 'myapp',
                destinationTag: 'promoteQA')

          openshiftDeploy(namespace: 'testing',
                    deploymentConfig: 'myapp',
                  waitTime: '300000')

          openshiftScale(namespace: 'testing',
                    deploymentConfig: 'myapp',
                  waitTime: '300000',
                  replicaCount: '2')

          stage 'verify deploy in test'
          openshiftVerifyDeployment(namespace: 'testing',
                      depCfg: 'myapp',
                      replicaCount:'2',
                      verifyReplicaCount: 'true',
                      waitTime: '300000')

          stage 'Deploy to production'
          timeout(time: 2, unit: 'DAYS') {
              input message: 'Approve to production?'
        }

          openshiftTag(namespace: 'development',
                  sourceStream: 'myapp',
                sourceTag: 'promoteQA',
                destinationStream: 'myapp',
                destinationTag: 'promotePRD')


          openshiftDeploy(namespace: 'production',
                    deploymentConfig: 'myapp',
                  waitTime: '300000')

          openshiftScale(namespace: 'production',
                    deploymentConfig: 'myapp',
                  waitTime: '300000',
                  replicaCount: '2')

          stage 'verify deploy in production'
          openshiftVerifyDeployment(namespace: 'production',
                      depCfg: 'myapp',
                      replicaCount:'2',
                      verifyReplicaCount: 'true',
                      waitTime: '300000')
        }
    type: JenkinsPipeline
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
  - imageChange:
      from:
        kind: ImageStreamTag
        name: 'centos-httpd:latest'
        namespace: development
    type: ImageChange
status:
  lastVersion: 0
